//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpRSS.FeedParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpRSS.FeedParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be empty.
        /// </summary>
        internal static string ErrorMessage_EmptyFeedString {
            get {
                return ResourceManager.GetString("ErrorMessage_EmptyFeedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not valid XML.
        /// </summary>
        internal static string ErrorMessage_InvalidXmlString {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidXmlString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;channel&gt; element is missing.
        /// </summary>
        internal static string ErrorMessage_MissingChannel {
            get {
                return ResourceManager.GetString("ErrorMessage_MissingChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS feed is not version 2.
        /// </summary>
        internal static string ErrorMessage_NonRss2RootString {
            get {
                return ResourceManager.GetString("ErrorMessage_NonRss2RootString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root node is not &lt;rss&gt;.
        /// </summary>
        internal static string ErrorMessage_NonRssRootString {
            get {
                return ResourceManager.GetString("ErrorMessage_NonRssRootString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to parse into xml: {RssFeed}.
        /// </summary>
        internal static string FeedParser_Logger_AttemptXmlParsing {
            get {
                return ResourceManager.GetString("FeedParser_Logger_AttemptXmlParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning {ElementName} value of {Value}.
        /// </summary>
        internal static string FeedParser_Logger_BasicSet {
            get {
                return ResourceManager.GetString("FeedParser_Logger_BasicSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin parsing feed.
        /// </summary>
        internal static string FeedParser_Logger_BeginParsing {
            get {
                return ResourceManager.GetString("FeedParser_Logger_BeginParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently parsing {Element}.
        /// </summary>
        internal static string FeedParser_Logger_CurrentElement {
            get {
                return ResourceManager.GetString("FeedParser_Logger_CurrentElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse feed - passed string is empty / only whitespace.
        /// </summary>
        internal static string FeedParser_Logger_EmptyString {
            get {
                return ResourceManager.GetString("FeedParser_Logger_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessing root element {Root} of parsed xml document.
        /// </summary>
        internal static string FeedParser_Logger_GetRootElement {
            get {
                return ResourceManager.GetString("FeedParser_Logger_GetRootElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {Value} to {ListName} list.
        /// </summary>
        internal static string FeedParser_Logger_ListItemAdded {
            get {
                return ResourceManager.GetString("FeedParser_Logger_ListItemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;channel&gt; element is missing.
        /// </summary>
        internal static string FeedParser_Logger_MissingChannel {
            get {
                return ResourceManager.GetString("FeedParser_Logger_MissingChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered non-rss root element: {RootName}.
        /// </summary>
        internal static string FeedParser_Logger_NonRssRootElement {
            get {
                return ResourceManager.GetString("FeedParser_Logger_NonRssRootElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse feed - passed string is null.
        /// </summary>
        internal static string FeedParser_Logger_NullString {
            get {
                return ResourceManager.GetString("FeedParser_Logger_NullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse Source from {Element} because of missing url attribute.
        /// </summary>
        internal static string FeedParser_Logger_SourceUrlMissing {
            get {
                return ResourceManager.GetString("FeedParser_Logger_SourceUrlMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed parsing {Value} into {Type} for {Property}.
        /// </summary>
        internal static string FeedParser_Logger_TryParseFailed {
            get {
                return ResourceManager.GetString("FeedParser_Logger_TryParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered unknown rss version: {RssVersion}.
        /// </summary>
        internal static string FeedParser_Logger_UnknownRssVersion {
            get {
                return ResourceManager.GetString("FeedParser_Logger_UnknownRssVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully parsed string into xml: {XmlDoc}.
        /// </summary>
        internal static string FeedParser_Logger_XmlParsed {
            get {
                return ResourceManager.GetString("FeedParser_Logger_XmlParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered exception while parsing feed string {FeedString} into xml document: {Exception}.
        /// </summary>
        internal static string FeedParser_Logger_XmlParseFailed {
            get {
                return ResourceManager.GetString("FeedParser_Logger_XmlParseFailed", resourceCulture);
            }
        }
    }
}
